### ISSUE TITLE
Playwright - Is there a way to configure saucectl to use customer reporter from playright.config file

### ISSUE THREAD

**Issue by aaa-vinaydara** [saucelabs/saucectl-playwright-example#25]
I have my playwright config file setup with the reporter option as below - 
reporter: [
    ['./utils/custom-reporter.ts'],
    ['html', { open: 'never' }],
  ],

How can I configure saucectl yml file to run the test with this reporter option?

**Comment by NerdishShah** [comment]
I was assuming the reports configured in playwright config would be populated on saucectl run, whats the point of configFile in playwright block of sauce config yml (The given reference link is also broken)

`playwright:
  version: package.json # See https://docs.saucelabs.com/dev/cli/saucectl/#supported-frameworks-and-browsers for a list of supported versions.
  configFile: playwright.config.js # See https://docs.saucelabs.com/dev/testrunner-toolkit/configuration/playwright#configuration-examples for a list of supported configuration files.`

https://github.com/saucelabs/saucectl-playwright-example/blob/0932041436d5f117a28921dbbf397e3138fa53e3/.sauce/config.yml#L18
