### ISSUE TITLE
globalSetup file is invoked multiple times during execution

### ISSUE THREAD

**Issue by aaa-vinaydara** [saucelabs/saucectl-playwright-example#27]
I have a globalSetup file configured as per the following - https://playwright.dev/docs/test-advanced#global-setup-and-teardown

In my config.yml, if I have multiple suites defined and if I run saucectl with concurrency set to 2, then globalSetup file is invoked twice.

**Comment by alexplischke** [comment]
Please file any issues under https://github.com/saucelabs/saucectl 🙏 Don't forget to provide additional details, like a link to a sample job you ran.

**Comment by aaa-vinaydara** [comment]
@alexplischke Thanks. Will open issues as indicated in future. Is this issue fixed? Or do I need to replicate this under  https://github.com/saucelabs/saucectl?

**Comment by alexplischke** [comment]
> Is this issue fixed?

Nope :) 

> Or do I need to replicate this under https://github.com/saucelabs/saucectl?

Correct! And please don't forget to add additional information (job link at a minimum, which saucectl version, anything that can be helpful).
