### ISSUE TITLE
broken 'transpile them to JavaScript' link in the documentation

### ISSUE THREAD

**Issue by ychaudhari** [saucelabs/saucectl-playwright-example#28]
We have all tests written in typescript, and I was looking for a way to run them with saucectl, which suggests to transpile them. However the link on the documentation is broken:
https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#transpiling-typescript-tests seems to go nowhere

**Comment by alexplischke** [comment]
Playwright supports typescript out of the box, so no transpilation required when using it with saucectl :) You can try it out in this example repo by changing the test to typescript and adjusting the test pattern.
