### ISSUE TITLE
11:48:55 ERR failed to execute run command error="unable to determine available versions for framework: unexpected status '401' from test-composer: Unauthorized\n"

### ISSUE THREAD

**Issue by jonbeacherdomuso** [saucelabs/saucectl-playwright-example#34]
`11:48:55 ERR failed to execute run command error="unable to determine available versions for framework: unexpected status '401' from test-composer: Unauthorized\n"`

**Steps to reproduce issue**
1 Download Docker Desktop on Mac and start
2. Follow Example tutorial
3. Expect: Example to run without issues
4. Actual:

`jon@jons-MBP saucectl-playwright-example % saucectl run`          

`Running version 0.107.2`
`11:53:33 INF Running Playwright in Sauce Labs`

                                        (.                          
                                       #.                           
                                       #.                           
                           .####################                    
                         #####////////*******/######                
                       .##///////*****************###/              
                      ,###////*********************###              
                      ####//***********************####             
                       ###/************************###              
                        ######********************###. ##           
                           (########################  ##     ##     
                                   ,######(#*         ##*   (##     
                               /############*          #####        
                           (########(  #########(    ###            
                         .#######,    */  ############              
                      ,##########  %#### , ########*                
                    *### .#######/  ##  / ########                  
                   ###   .###########//###########                  
               ######     ########################                  
             (#(    *#(     #######.    (#######                    
                    ##,    /########    ########                    
                           *########    ########                    

`11:53:33 ERR failed to execute run command error="unable to determine available versions for framework: unexpected status '401' from test-composer: Unauthorized\n"
jon@jons-MBP saucectl-playwright-example % `

**Comment by alexplischke** [comment]
It looks like your credentials are not set (correctly). If you have set them, perhaps they contain a typo?
