### ISSUE TITLE
I want to run my webapp tests on mobile browsers 

### ISSUE THREAD

**Issue by sekharsdet** [saucelabs/saucectl-playwright-example#47]
Could you please share an example **sauce** config.yml where I can run my web tests on mobile browsers? Example. Mobile Safari and Mobile Chome

**Comment by alexplischke** [comment]
Playwright does not run on mobile devices. It does have a concept of [emulation](https://playwright.dev/docs/emulation), but that's just setting the viewport to same size that you'd expect from a mobile device.
