### ISSUE TITLE
Example on how to test in Google Chrome

### ISSUE THREAD

**Issue by marian-r** [saucelabs/saucectl-playwright-example#68]
The SauceLabs [documentation says `chrome` is supported](https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#browsername) as the browser option. Would it be possible to add an example using this browser?

When I tried using it I get the following error:

```
Error: browserType.launch: Chromium distribution 'chrome' is not found at C:\Users\sauce\AppData\Local\Google\Chrome\Application\chrome.exe
```

Has anybody been able to run Playwright tests in Chrome on SauceLabs?

**Comment by alexplischke** [comment]
Are you by any chance using a Sauce Connect tunnel? We've discovered an issue that prevents the combination of playwright + chrome _when using a Sauce Connect tunnel_. The other browsers are not impacted by this. We have a fix ready that's scheduled for our upcoming playwright release (end of August, early September).

**Comment by marian-r** [comment]
Thanks for a quick answer. Yes, I am using the tunnel, so that might be it. I will wait for the release you mentioned. Thanks.

**Comment by marian-r** [comment]
I can confirm this issue is no longer present. Thank you 👍

**Comment by Balajiiguru** [comment]
I am still facing the exact same issue. I am using playwright version 1.39  and try to run in chrome and I am using sauce tunnel.. can you whether the fix is abailable for this issue?
