### ISSUE TITLE
Saucectl installation failed

### ISSUE THREAD

**Issue by SridharRamachandran** [saucelabs/saucectl-playwright-example#72]
In our organisation we are using sauce integrated with Java and cucumber BDD project. And now we have migrated to Playwright with cucumberJS and thought of implementing playwright on it.

note : we are running from our local machine and sauce username and key is set in system env variable and it is fetched successfully using set %SAUCE_USERNAME%

on running below command we are getting error message 

yarn add saucectl 

error : Fetching saucectl binary
Installation failed : Error : Failed to download : AxiosError : Unsupported protocol c
Check that you have access to https://GitHub.com/saucelabs or format of the saucectl install binary environment variable is correct

Note : Even tried using export sauce_install_binary=localmachinepath of saucectl.tar.gz yarn add saucectl

Same error for above one as well 

Config.yml is set under .sauce folder as well

**Comment by SridharRamachandran** [comment]
In addition to above error - Fetching saucectl binary
Installation failed : Error : failed to download : Error : connect EConnrefused :: 1 : 80

**Comment by SridharRamachandran** [comment]
Error much more detailed : c:/…./node_modules/saucectl: command failed 
Exit code : 1

arguments: Directory :C:/…/saucectl 
Output : fetching saucectl binary
Installation failed

**Comment by alexplischke** [comment]
`SAUCECTL_INSTALL_BINARY` requires a web URL, not a local file path.

If you are already downloading the binary directly, e.g. from https://github.com/saucelabs/saucectl/releases), don't bother installing it via yarn/npm. Just extract the binary and use it directly :)

The installation via npm/yarn is provided as a convenience option only.
