### ISSUE TITLE
Not able to run test in chrome browser in sauce lab along with sauce tunnel

### ISSUE THREAD

**Issue by Balajiiguru** [saucelabs/saucectl-playwright-example#76]
On trying to run the playwright test in saucelabs with sauce tunnel in chrome browser, I am getting the below error

Error: browsertype.launch: chromium distribution not found at c:\users\sauce\AppData\Local\Google\Chrome\Application\chrome.exe

Desired behavior

Should able to execute the test in sauce lab with sauce tunnel ebabled in chrome browser

Config to reproduce

I can’t able to share due to company policy

Versions

Os : windows 11
Saucetl : 0.165
Bowser: chrome
Playwright version: 1.39.0

**Comment by alexplischke** [comment]
Does your `playwright.config.js/ts` use project specific `launchOptions` when running on Sauce? If so, please remove them, as they override our global tunnel settings.

**Comment by Balajiiguru** [comment]
Without launchoptions it is working fine.
